class Error:
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	INVALID_PARAMETERS = "INVALID_PARAMETERS"
	NO_DATA_FOUND = "NO_DATA_FOUND"
	ALREADY_EXISTS = "ALREADY_EXISTS"
	UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
	VALIDATION_ERRORS = "VALIDATION_ERRORS"
	PAGE_NOT_FOUND = "PAGE_NOT_FOUND"
	USER_NOT_FOUND = "USER_NOT_FOUND"
	ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
	INVALID_STRING_LENGTH = 'INVALID_STRING_LENGTH'
