# Generated by Django 4.2.2 on 2023-06-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_freshjuice_item_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fresh_juice', 'fresh_juice'), ('milk_shake', 'milk_shake'), ('special_milk_shake', 'special_milk_shake'), ('bonanza', 'bonanza'), ('hot_drinks', 'hot_drinks'), ('healthy_juice', 'healthy_juice'), ('lassi', 'lassi'), ('cold', 'cold'), ('falooda', 'falooda'), ('soda', 'soda'), ('icecream', 'icecream'), ('icecream_shake', 'icecream_shake'), ('choco_spl', 'choco_spl')], default='fresh_juice', max_length=50),
        ),
    ]
